create database if not exists aeda_metadata;

use aeda_metadata;

CREATE TABLE IF NOT EXISTS columns (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , COLUMN_NAME NVARCHAR(255) DEFAULT NULL
      , ORDINAL_POSITION INT DEFAULT NULL
      , DATA_TYPE NVARCHAR(255) DEFAULT NULL);
      
CREATE TABLE IF NOT EXISTS tables (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , N_COLUMNS INT DEFAULT NULL
      , N_ROWS INT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS uniques (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , COLUMN_NAME NVARCHAR(255) DEFAULT NULL
      , ORDINAL_POSITION INT DEFAULT NULL
      , DATA_TYPE NVARCHAR(255) DEFAULT NULL
      , DISTINCT_VALUES INT DEFAULT NULL
      , NULL_VALUES INT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS data_values (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , COLUMN_NAME NVARCHAR(255) DEFAULT NULL
      , DATA_VALUE NVARCHAR(255) DEFAULT NULL
      , FREQUENCY_NUMBER INT DEFAULT NULL
      , FREQUENCY_PERCENTAGE FLOAT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS dates (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , COLUMN_NAME NVARCHAR(255) DEFAULT NULL
      , DATA_VALUE NVARCHAR(255) DEFAULT NULL
      , FREQUENCY_NUMBER INT DEFAULT NULL
      , FREQUENCY_PERCENTAGE FLOAT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS stats (SERVER_NAME NVARCHAR(255)
      , TABLE_CATALOG NVARCHAR(255) DEFAULT NULL
      , TABLE_SCHEMA NVARCHAR(255) DEFAULT NULL
      , TABLE_NAME NVARCHAR(255) DEFAULT NULL
      , COLUMN_NAME NVARCHAR(255) DEFAULT NULL
      , AVG FLOAT DEFAULT NULL
      , STDEV FLOAT DEFAULT NULL
      , "VAR" FLOAT DEFAULT NULL
      , SUM FLOAT DEFAULT NULL
      , MAX FLOAT DEFAULT NULL
      , MIN FLOAT DEFAULT NULL
      , "RANGE" FLOAT DEFAULT NULL
      , P01 FLOAT DEFAULT NULL
      , P025 FLOAT DEFAULT NULL
      , P05 FLOAT DEFAULT NULL
      , P10 FLOAT DEFAULT NULL
      , Q1 FLOAT DEFAULT NULL
      , Q2 FLOAT DEFAULT NULL
      , Q3 FLOAT DEFAULT NULL
      , P90 FLOAT DEFAULT NULL
      , P95 FLOAT DEFAULT NULL
      , P975 FLOAT DEFAULT NULL
      , P99 FLOAT DEFAULT NULL
      , IQR FLOAT DEFAULT NULL);


CREATE VIEW IF NOT EXISTS servers AS 
select      server_name
            , table_catalog 
            , table_schema 
            , count(distinct table_name) as n_tables
            , sum(n_columns) as n_columns 
            , sum(n_rows) as n_rows 
from tables
group by server_name, table_catalog , table_schema;
